### ISSUE TITLE
툴바 구현

### ISSUE THREAD

**Issue by the1020** [LemonScone/check-it-out#4]
- [x] `start` 버튼이 우측에 위치한다.
- [x] `start` 버튼을 클릭하면 글자가 `stop`으로 변경되고 버튼 색상이 빨간색으로 변경된다.
- [x] `start` 버튼을 클릭하면 시작시간이 현재시각으로 표시된다.
  - [x] 시작시간 포맷 yyyy/mm/dd 
- [x] `start` 버튼을 클릭하면 종료시간이 "작업중"으로 표시된다.
- [x] `stop` 버튼을 클릭하면 종료시간이 현재시각으로 표시된다.
- [x] 중앙에 시작시간, 종료시간, 총 작업시간을 보여준다.
  - [x] 시작시간, 종료시간, 총 작업시간은 hh:mm:ss 포맷으로 출력한다.
- [x] 날짜를 이동할 수 있는 버튼이 좌측에 위치한다. (electron-store에 저장)
  - [x] `<` 버튼을 클릭하면 이전 날짜로 변경되고, 이전 날짜의 작업 결과가 그래프와 작업 목록에 표시된다.
  - [x] `>` 버튼을 클릭하면 다음 날짜로 변경되고, 다음 날짜의 작업 결과가 그래프와 작업 목록에 표시된다.
  - [x] 현재 날짜이면  `>` 버튼은 비활성화된다.
- [x] 오늘 날짜로 이동 버튼 추가

**Comment by padosum** [comment]
단축키로 시작/일시정지를 할 수 있으면 좋을 것 같다는 생각이 들었습니다..
